site_name: Python App Template

repo_url: https://github.com/tomharrisonjr/python-app-template

docs_dir: docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.instant

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [ src ]

nav: []

use_directory_urls: false
