---
name: Release

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    concurrency: release

    steps:
      steps:
        # checkout repo
        - name: Checkout repository
          uses: actions/checkout@v3
          with:
            ref: ${{ github.head_ref }}
            token: ${{ secrets.GH_TOKEN }}
            fetch-depth: 0
        # install poetry
        - name: Install poetry
          run: pipx install poetry==${{ vars.POETRY_VERSION }}
          # set up python with cache
        - name: Setup python ${{ vars.PYTHON_VERSION }}
          uses: actions/setup-python@v4
          with:
            python-version: ${{ vars.PYTHON_VERSION }}
            cache: 'poetry'
        # Install requirements (including dev-dependencies)
        - name: Install requirements
          run: poetry install --only semver
        # Run semantic-release
        - name: Run semantic-release
          env:
            GH_TOKEN: ${{ secrets.GH_TOKEN }}
          run: |
            set -o pipefail
            git config --global user.name "semantic-release (bot)"
            git config --global user.email "github-actions@github.com"
            poetry run semantic-release publish -v DEBUG -D commit_author="<semantic-release (bot)>github-actions@github.com"
